name: hoynet
channels:
  - pytorch
  - defaults
  - pyg
dependencies:
  - python=3.9
  - pandas
  - numpy
  - pyyaml
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - black
  - scikit-learn
  - pyg  # This is the line added for PyTorch Geometric (pyG)