train:
  device: cuda:0
  target: ./train_3/fin2vec.yml
  data2vec: ./train_3/data2vec.yml
  data: 
    priceFile : ./data/data_2.csv
    codeFile : ./data/NASDAQ_FC_STK_IEM_IFO.csv
  epochs: 500
  batches: 60
  lr: 0.0001
  testRate: 0.2
  ckpt: ./train_3/checkpoints