HoynetConfig:
  mode: "training"
  device: "cuda:0"
  models:
    pcrn:
      data:
        codeFile: "./data/NASDAQ_FC_STK_IEM_IFO.csv"
        priceFile: "./data/data_2.csv"
      train:
        epochs: 500
        batches: 30
        lr: 0.0001
        eval: 0.2
        ckpt: ./checkpoints
      config:
        term: 300
        inputs: ["Open", "High", "Low", "Close", "Volume"]
        outputs: ["Open", "Close"]
        hiddens: 64
        nlayers: 7
        fusions: 32
        embeddings: 10,10
      # models: path....
    fin2vec:
      encoder: "./pretrained/pcrn/hoynet_270.pth"
      type_: "finance"
      pcrn:
        data:
          codeFile: "./data/NASDAQ_FC_STK_IEM_IFO.csv"
          priceFile: "./data/data_2.csv"
        config:
          term: 300
          inputs: ["Open", "High", "Low", "Close", "Volume"]
          outputs: ["Open", "Close"]
          hiddens: 64
          nlayers: 7
          fusions: 32
          embeddings: 10,10
      d2v:
        config:
          type_: "finance"
          device: "cuda:0"
          embed_dim: 10
          ema_decay: 0.999
          ema_end_decay: 0.9999
          ema_anneal_end_step: 30000
      config:
        embeddings: 10,10
        outputs: 32
        d_model: 64
        nhead: 8
        d_hid: 64
        nlayers: 7 
        dropout: 0.2
      train:
        epochs: 500
        batches: 60
        lr: 0.0001
        eval: 0.2
        ckpt: ./checkpoints/ckpt_10-12_b
        
