train:
  device: cpu
  target: ./demo/config/pcrn.yml
  data: 
    priceFile : ./data/data_2.csv
    codeFile : ./data/NASDAQ_FC_STK_IEM_IFO.csv
  epochs: 500
  batches: 60
  lr: 0.0001
  trainRate: 0.2
  ckpt: ./ # path to checkpoint