pcrn:
  term: 100
  inputs: ["Open", "High", "Low", "Close", "Volume", "gold", "bond"]
  outputs: ["Open", "Close"]
  hiddens: 64
  nlayers: 7
  fusions: 32
  embeddings: 20,1
  data: ../crawling/NASDAQ/E_NASDAQ_DATA.csv
  weight: ./train0/ckpt/pcrn_0_860.pth
  