pcrn:
  term: 300
  inputs: ["Open", "High", "Low", "Close", "Volume"]
  outputs: ["Open", "Close"]
  hiddens: 64
  nlayers: 7
  fusions: 32
  embeddings: 10,10
  data: ./data/data_2.csv
  weight: ./pretrained/pcrn/hoynet_270.pth